apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reservation-pvc
  labels:
    app: reservation-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ki
  storageClassName: azurefile