server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/** 
        - id: vaccine
          uri: http://localhost:8082
          predicates:
            - Path=/vaccineMgmts/** 
        - id: myPage
          uri: http://localhost:8083
          predicates:
            - Path= /myPages/**
        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: vaccine
          uri: http://vaccine:8080
          predicates:
            - Path=/vaccineMgmts/** 
        - id: myPage
          uri: http://myPage:8080
          predicates:
            - Path= /myPages/**
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080